PACKAGE_NAME="cv181x-camera"
PACKAGE_VERSION="#MODULE_VERSION#"

BUILT_MODULE_NAME[0]="cv181x-camera-common"
BUILT_MODULE_NAME[1]="cv181x-csi2"
BUILT_MODULE_NAME[2]="cv181x-vi"
BUILT_MODULE_NAME[3]="cv181x-isp"
BUILT_MODULE_NAME[4]="cv181x-vip"

DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"
DEST_MODULE_LOCATION[3]="/updates/dkms"
DEST_MODULE_LOCATION[4]="/updates/dkms"

AUTOINSTALL="yes"
BUILD_EXCLUSIVE_ARCH="riscv64"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
